all:
	echo '' | cat > Results.out 
	echo '' | cat > DVS_logs.out 
	echo '' | cat > DVS_Priority_logs.out 
	echo '' | cat > DVS_DPM_logs.out 

	python3.10 main.py --file set_test.sch
	python3.10 main.py --file set_test2.sch
	python3.10 main.py --file set_test3.sch
	python3.10 main.py --file set_test4.sch
	python3.10 main.py --file set_test5.sch
	python3.10 main.py --file set_test6.sch